version: "3.3"
services: 
  db:
    image: mariadb
    restart: always
    networks:
      - backend_data
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb

  php:
    build: ./php
    depends_on:
      - db
    environment:
      - DB_1_ENV_MYSQL_HOST=db
      - DB_1_ENV_MYSQL_USER=root
      - DB_1_ENV_MYSQL_PASSWORD=mariadb
    networks:
      - backend
      - backend_data
    ports: 
      - 9000:9000
    expose: 
      - 9000  
    volumes:
      - ../app/:/var/www/html  
      - ../logs/php:/var/log:rw    

  apache:
    build: ./apache
    depends_on:
      - php
    hostname: httpd_host  
    networks:
      - backend
      - frontend
    ports: 
      - 8080:80
    volumes:
      - ../app/:/usr/local/apache2/htdocs/
      - ../logs/apache:/usr/local/apache2/logs:rw

networks:
  backend_data:
  backend:
  frontend: