version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    networks:
      - backend_data
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    volumes: 
      - '../var/mysql:/var/lib/mysql'  
  php:
    build: ./php
    depends_on:
      - db
    environment:
      - DB_1_ENV_MYSQL_HOST=db
      - DB_1_ENV_MYSQL_USER=root
      - DB_1_ENV_MYSQL_PASSWORD=mariadb
    networks:
      - backend
      - backend_data
    volumes:
      - '../app/:/var/www/html'
      - '../var/logs/php:/var/log:rw'
  apache:
    build: ./apache
    depends_on:
      - php
    hostname: httpd_host
    networks:
      - backend
      - frontend
    ports:
      - '8080:80'
    volumes:
      - '../app/:/usr/local/apache2/htdocs/'
      - '../var/logs/apache:/usr/local/apache2/logs:rw'
networks:
  backend_data: null
  backend: null
  frontend: null
